# Get all blogs
GET http://localhost:3003/api/blogs
###

# Create a new blog
POST http://localhost:3003/api/blogs
content-type: application/json
# Authorization: Bearer thisIsAnInvalidToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsb2dtYWtlciIsImlkIjoiNWY4MTIzMTUwYTgzY2M1MTFjNDg0ZWYxIiwiaWF0IjoxNjAyMzgwMjkzfQ.0EM8zPk1UVO0BeDOEXncvicJd100Ded_rAS78R8zI_8

{
    "title": "Title 11",
    "author": "Author",
    "url": "https://blog-0012.com/",
    "likes": 1
}
###

# Delete a blog created by the user
DELETE http://localhost:3003/api/blogs/5f8280196e52074ab45b90e2
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJsb2dtYWtlciIsImlkIjoiNWY4MTIzMTUwYTgzY2M1MTFjNDg0ZWYxIiwiaWF0IjoxNjAyMzgwMjkzfQ.0EM8zPk1UVO0BeDOEXncvicJd100Ded_rAS78R8zI_8
###