GET http://localhost:3003/api/blogs

###
DELETE http://localhost:3003/api/blogs/1

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Title THREE",
    "author": "Author THREE",
    "url": "https://blog-THREE.com/",
    "likes": 21
}

###