# Get all users
GET http://localhost:3003/api/users
###

# Create a new user
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "blogmaker",
    "name": "Blog Maker",
    "password": "abc123ABC"
}
###

# Get the list of all users
GET http://localhost:3003/api/users
###

# Create a new user with a 2 characters long username (should be rejected)
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "ab",
    "name": "Norman",
    "password": "abc123ABC"
}
###

# Create a new user without password (should be rejected)
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "user5",
    "name": "Norman"
}
###

# Create a new user with a 2 characters long password (should be rejected)
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "user0",
    "name": "Norman",
    "password": "12"
}
###
